using Godot;
using Qkmaxware.Emulators.Gameboy;
using Qkmaxware.Emulators.Gameboy.Hardware;
using System;
using System.IO;
using System.Numerics;

public partial class Speakers : Control {

	[Export] public bool EnableSound = false;

    [ExportGroup("Icons")]
    [Export] public Texture2D AudioPlayingIcon;
    [Export] public Texture2D AudioPausedIcon;

	// Audio stream generator for playback
    private AudioStreamPlayer player;
    private AudioStreamGenerator generator;
    private AudioStreamGeneratorPlayback playback;

	// Buffer size for audio generation (in samples)
    private const int BufferSize = 1024;

	// Sample rate (GameBoy typically runs at 44100 Hz)
    private const int SampleRate = 44100;

	// Audio channel data
    private Godot.Vector2[] audioBuffer = new Godot.Vector2[BufferSize];

	public override void _Ready() {
        SetAudio(EnableSound);

        // Initialize the AudioStreamGenerator
        player = GetNode<AudioStreamPlayer>("Player");
        if (player.Stream is not AudioStreamGenerator stream) {
            return;
        }
        generator = stream;
        generator.MixRate = SampleRate;
        player.Play();
        
        playback = player.GetStreamPlayback() as AudioStreamGeneratorPlayback;
    }

    public void ToggleAudio() {
        SetAudio(!EnableSound);
    }
    public void SetAudio(bool enable) {
        EnableSound = enable;
    }

    public void GenerateAudio(Gameboy gameboy, double dt) {
        // Clear the buffer
        Array.Fill(audioBuffer, Godot.Vector2.Zero);

        // Generate the audio
        if (EnableSound)
            GenerateAudio(gameboy.Sound);

        // Fill the buffer for audio playback
        playback.PushBuffer(audioBuffer);
        return;
    }

	private void GenerateAudio(APU apu) {
        // Mix the sounds of all channels
        MixSquareWaveChannel(apu.Square1);
        MixSquareWaveChannel(apu.Square2);
        MixWaveChannel(apu.Wave);
        MixNoiseChannel(apu.Noise);
    }

	private void MixSquareWaveChannel(SquareWaveChannel channel) {
        // Sample rate and frequency calculation for square waves
        float frequency = CalculateFrequency(channel);
        float volume = CalculateVolume(channel);

        // Generate square wave for the channel
        for (int i = 0; i < BufferSize; i++)
        {
            // Create a simple square wave alternating between -1 and 1
            audioBuffer[i] += Godot.Vector2.One * GenerateSquareWave(frequency, i) * volume;
        }
    }

    private void MixWaveChannel(WaveChannel channel) {
        // Sample rate and frequency calculation for wave channel
        float frequency = CalculateFrequency(channel);
        float volume = CalculateVolume(channel);

        // Generate wave form for the channel
        for (int i = 0; i < BufferSize; i++)
        {
            // Placeholder for wave synthesis logic (example: a sine wave)
            audioBuffer[i] += Godot.Vector2.One * GenerateWave(frequency, i) * volume;
        }
    }

    private void MixNoiseChannel(NoiseChannel channel) {
        // Noise is more complex, typically generated by a Linear Feedback Shift Register (LFSR)
        float volume = CalculateVolume(channel);

        for (int i = 0; i < BufferSize; i++)
        {
            audioBuffer[i] += Godot.Vector2.One * GenerateNoise(i) * volume;
        }
    }

    private float GenerateSquareWave(float frequency, int sampleIndex) {
        // Generate a square wave alternating between -1 and 1
        float period = SampleRate / frequency;
        return MathF.Sign(MathF.Sin(2 * MathF.PI * sampleIndex / period));
    }

    private float GenerateWave(float frequency, int sampleIndex) {
        // Example of a sine wave as a placeholder for wave channel
        return MathF.Sin(2 * MathF.PI * frequency * sampleIndex / SampleRate);
    }

    private float GenerateNoise(int sampleIndex) {
        // Simple placeholder for generating noise, in reality, it would use an LFSR
        return (float)(GD.Randf() * 2 - 1); // Random noise between -1 and 1
    }

    private float CalculateFrequency(SquareWaveChannel channel) {
        int frequency = (channel.FrequencyMsb << 8) | channel.FrequencyLsb;
        return 131072f / (2048f - frequency); // GameBoy frequency calculation formula
    }

    private float CalculateFrequency(WaveChannel channel) {
        int frequency = (channel.FrequencyMsb << 8) | channel.FrequencyLsb;
        return 131072f / (2048f - frequency); // Same formula as Square Wave
    }

    private float CalculateFrequency(NoiseChannel channel) {
        int frequency = (channel.DivisorCode + 1) * 4;
        return 524288f / frequency; // Noise frequency calculation formula
    }

    private float CalculateVolume(Channel channel)  {
        // Simple volume mapping based on the channel's volume settings
        switch (channel)
        {
            case SquareWaveChannel sqChannel:
                return (sqChannel.StartingVolume.NormalizedPercent);
            case WaveChannel wChannel:
                return (float)wChannel.Volume / 3f;
            case NoiseChannel nChannel:
                return (nChannel.StartingVolume + 1) / 16f;
            default:
                return 0f;
        }
    }
}
