name: Release
on:
  release: 
    types: [ published, edited ]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        godot: [ 4.2.2-stable ]
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: '8.0.x' # SDK Version to use
    - name: .Net Core Info
      run: dotnet --info
    - name: Run Unit Tests
      run: dotnet test

  godot:
    needs: [ test ]
    name: Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix: 
        godot: [ '4.4.1' ]
        os: [ 'windows-latest' ]
        platform: [ 'win-x64' ]
        preset: [ 'Windows x64' ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
      with:
        lfs: true
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: '8.0.x' # SDK Version to use
    - name: Setup Directories
      run: New-Item -ItemType Directory "temp" -Force; New-Item -ItemType Directory "temp\Godot" -Force; New-Item -ItemType Directory "temp\Templates" -Force;
    
    - name: Download Godot
      run: Invoke-WebRequest "https://github.com/godotengine/godot/releases/download/${{ matrix.godot }}-stable/Godot_v${{ matrix.godot }}-stable_mono_win64.zip" -OutFile "temp\godot.zip"
    - name: Extract Godot 
      run: Expand-Archive -Path "temp\godot.zip" -DestinationPath "temp\Godot" -Force
    - name: Download Build Template
      run: Invoke-WebRequest "https://github.com/godotengine/godot/releases/download/${{ matrix.godot }}-stable/Godot_v${{ matrix.godot }}-stable_mono_export_templates.tpz" -OutFile "temp\templates.tpz"
    - name: Extract Build Templates
      run: tar -xvzf "temp\templates.tpz" -C "temp\Templates" 
    - name: Install Build Templates
      run: Copy-Item -Path "temp\Templates\templates" -Destination "$env:APPDATA\Godot\export_templates\${{ matrix.godot }}.stable.mono" -Recurse -Force

    - name: Build Binary
      run: New-Item -Force -Path "./bin" -ItemType "directory"; New-Item -Force -Path "./bin/${{ matrix.platform }}" -ItemType "directory"; New-Item -Force -Path "./bin/${{ matrix.platform }}/godot" -ItemType "directory"; .\temp\Godot\Godot_v${{ matrix.godot }}-stable_mono_win64_console.exe --headless --verbose --build-solutions --export-release ${{ matrix.preset }} "./bin/${{ matrix.platform }}/godot/BlazorBoy.exe" "./Gameboy.Player.Godot/project.godot"
    - name: Zip Binary
      run: echo "TODO"
    - name: Upload Binary
      run: echo "TODO"

  nuget:
    needs: [ test ]
    name: Publish Nuget
    permissions:
      packages: write
    strategy: 
      fail-fast: false
      matrix: 
        os: [ windows-latest ]
        dotnet: [ '8.0.x' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: '${{ matrix.dotnet }}' # SDK Version to use
    - name: Pack CPU Nuget Package
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
      run: dotnet pack Qkmaxware.Vm.LR35902 --configuration Release --output nupkg
    - name: Pack Library Nuget Package
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
      run: dotnet pack Gameboy --configuration Release --output nupkg
    - name: Pack CLI Nuget Package
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
      run: dotnet pack Gameboy.Player.Cli --configuration Release --output nupkg
    - name: Publish Nuget Packages
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push nupkg\*.nupkg --source "https://nuget.pkg.github.com/qkmaxware/index.json" --skip-duplicate --api-key $Env:GITHUB_TOKEN

  blazor:
    name: Deploy Github Pages
    needs: [ test ]
    permissions:
      packages: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3 
        with:
          dotnet-version: '8.0.x' # SDK Version to use

      - name: Testing
        run: dotnet test Gameboy.Test

      - name: Change base-tag
        run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorBoy\/" \/>/g' Gameboy.Player.Blazor/wwwroot/index.html

      - name: Restore Packages
        env: 
          GITHUB_USERNAME: qkmaxware
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore

      - name: Build Site
        env: 
          GITHUB_USERNAME: qkmaxware
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet publish Gameboy.Player.Blazor -c Release -o .site     

      - name: Add .nojekyll file
        run: touch .site/wwwroot/.nojekyll

      - name: Custom 404
        run: cp .site/wwwroot/index.html .site/wwwroot/404.html

      - name: Commit to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .site/wwwroot